# Generated by Django 5.2 on 2025-04-16 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model_year', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'available'), ('not available', 'not available')], max_length=30)),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTSapp.jobtype')),
            ],
        ),
    ]
