# Generated by Django 5.1.7 on 2025-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTSapp', '0003_student_job_application_delete_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
