# Generated by Django 5.2 on 2025-05-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
