# Generated by Django 5.2 on 2025-05-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
