# Generated by Django 5.2 on 2025-05-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_application_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
