# Generated by Django 5.2 on 2025-05-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_employerprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='photo',
        ),
    ]
